import config from "../../config";

export const unitTypes = {
  url: `${config.services.mdm.uri}/unit-type-codes`,
  data: [
    {
      unitTypeCode: "AF",
      unitTypeDescription: "Arch-fired boiler",
      sortOrder: null,
      unitTypeGroupCode: "B",
      unitTypeGroupDescription: "Boilers",
    },
    {
      unitTypeCode: "BFB",
      unitTypeDescription: "Bubbling fluidized bed boiler",
      sortOrder: null,
      unitTypeGroupCode: "B",
      unitTypeGroupDescription: "Boilers",
    },
    {
      unitTypeCode: "C",
      unitTypeDescription: "Cyclone boiler",
      sortOrder: null,
      unitTypeGroupCode: "B",
      unitTypeGroupDescription: "Boilers",
    },
  ],
};

export const fuelTypes = {
  url: `${config.services.mdm.uri}/fuel-type-codes`,
  data: [
    {
      fuelTypeCode: "C",
      fuelTypeDescription: "Coal",
      fuelGroupCode: "COAL",
      fuelGroupDescription: "All Coal",
    },
    {
      fuelTypeCode: "CRF",
      fuelTypeDescription: "Coal Refuse",
      fuelGroupCode: "COAL",
      fuelGroupDescription: "All Coal",
    },
    {
      fuelTypeCode: "DSL",
      fuelTypeDescription: "Diesel Oil",
      fuelGroupCode: "OIL",
      fuelGroupDescription: "All Oil",
    },
  ],
};

export const states = {
  url: `${config.services.mdm.uri}/state-codes`,
  data: [
    { stateCode: "AK", stateName: "Alaska", epaRegion: 10 },
    { stateCode: "AL", stateName: "Alabama", epaRegion: 4 },
    { stateCode: "AR", stateName: "Arkansas", epaRegion: 6 },
    { stateCode: "AS", stateName: "American Samoa", epaRegion: 9 },
    { stateCode: "AZ", stateName: "Arizona", epaRegion: 9 },
    { stateCode: "CA", stateName: "California", epaRegion: 9 },
    { stateCode: "CO", stateName: "Colorado", epaRegion: 8 },
    { stateCode: "CT", stateName: "Connecticut", epaRegion: 1 },
    { stateCode: "DC", stateName: "District Of Columbia", epaRegion: 3 },
    { stateCode: "DE", stateName: "Delaware", epaRegion: 3 },
    { stateCode: "FL", stateName: "Florida", epaRegion: 4 },
    { stateCode: "FM", stateName: "States Of Micronesia", epaRegion: 9 },
    { stateCode: "GA", stateName: "Georgia", epaRegion: 4 },
    { stateCode: "GU", stateName: "Guam", epaRegion: 9 },
    { stateCode: "HI", stateName: "Hawaii", epaRegion: 9 },
    { stateCode: "IA", stateName: "Iowa", epaRegion: 7 },
    { stateCode: "ID", stateName: "Idaho", epaRegion: 10 },
    { stateCode: "IL", stateName: "Illinois", epaRegion: 5 },
    { stateCode: "IN", stateName: "Indiana", epaRegion: 5 },
    { stateCode: "KS", stateName: "Kansas", epaRegion: 7 },
    { stateCode: "KY", stateName: "Kentucky", epaRegion: 4 },
    { stateCode: "LA", stateName: "Louisiana", epaRegion: 6 },
    { stateCode: "MA", stateName: "Massachusetts", epaRegion: 1 },
    { stateCode: "MD", stateName: "Maryland", epaRegion: 3 },
    { stateCode: "ME", stateName: "Maine", epaRegion: 1 },
    { stateCode: "MH", stateName: "Marshall Islands", epaRegion: 9 },
    { stateCode: "MI", stateName: "Michigan", epaRegion: 5 },
    { stateCode: "MN", stateName: "Minnesota", epaRegion: 5 },
    { stateCode: "MO", stateName: "Missouri", epaRegion: 7 },
    { stateCode: "MP", stateName: "Northern Mariana Isl", epaRegion: 9 },
    { stateCode: "MS", stateName: "Mississippi", epaRegion: 4 },
    { stateCode: "MT", stateName: "Montana", epaRegion: 8 },
    { stateCode: "NC", stateName: "North Carolina", epaRegion: 4 },
    { stateCode: "ND", stateName: "North Dakota", epaRegion: 8 },
    { stateCode: "NE", stateName: "Nebraska", epaRegion: 7 },
    { stateCode: "NH", stateName: "New Hampshire", epaRegion: 1 },
    { stateCode: "NJ", stateName: "New Jersey", epaRegion: 2 },
    { stateCode: "NM", stateName: "New Mexico", epaRegion: 6 },
    { stateCode: "NV", stateName: "Nevada", epaRegion: 9 },
    { stateCode: "NY", stateName: "New York", epaRegion: 2 },
    { stateCode: "OH", stateName: "Ohio", epaRegion: 5 },
    { stateCode: "OK", stateName: "Oklahoma", epaRegion: 6 },
    { stateCode: "OR", stateName: "Oregon", epaRegion: 10 },
    { stateCode: "PA", stateName: "Pennsylvania", epaRegion: 3 },
    { stateCode: "PR", stateName: "Puerto Rico", epaRegion: 2 },
    { stateCode: "PW", stateName: "Palau", epaRegion: 9 },
    { stateCode: "RI", stateName: "Rhode Island", epaRegion: 1 },
    { stateCode: "SC", stateName: "South Carolina", epaRegion: 4 },
    { stateCode: "SD", stateName: "South Dakota", epaRegion: 8 },
    { stateCode: "TN", stateName: "Tennessee", epaRegion: 4 },
    { stateCode: "TX", stateName: "Texas", epaRegion: 6 },
    { stateCode: "UM", stateName: "Midway Islands", epaRegion: 9 },
    { stateCode: "UT", stateName: "Utah", epaRegion: 8 },
    { stateCode: "VA", stateName: "Virginia", epaRegion: 3 },
    { stateCode: "VI", stateName: "Virgin Islands", epaRegion: 2 },
    { stateCode: "VT", stateName: "Vermont", epaRegion: 1 },
    { stateCode: "WA", stateName: "Washington", epaRegion: 10 },
    { stateCode: "WI", stateName: "Wisconsin", epaRegion: 5 },
    { stateCode: "WV", stateName: "West Virginia", epaRegion: 3 },
    { stateCode: "WY", stateName: "Wyoming", epaRegion: 8 },
  ],
};

export const controlTechnologies = {
  url: `${config.services.mdm.uri}/control-codes`,
  data: [
    {
      controlCode: "APAC",
      controlDescription:
        "Additives to Enhance PAC and Existing Equipment Performance",
      controlEquipParamCode: "HG",
      controlEquipParamDescription: "Mercury",
    },
    {
      controlCode: "B",
      controlDescription: "Baghouse",
      controlEquipParamCode: "PART",
      controlEquipParamDescription: "Particulates (Opacity)",
    },
    {
      controlCode: "C",
      controlDescription: "Cyclone",
      controlEquipParamCode: "PART",
      controlEquipParamDescription: "Particulates (Opacity)",
    },
  ],
};

export const accountTypes = {
  url: `${config.services.mdm.uri}/account-type-codes`,
  data: [
    {
      accountTypeCode: "CASURR",
      accountTypeDescription: "Compliance Assurance Surrender Account",
      accountTypeGroupCode: "RETIRE",
      accountTypeGroupDescription: "Surrender",
    },
    {
      accountTypeCode: "ENFSURR",
      accountTypeDescription: "Enforcement Surrender Account",
      accountTypeGroupCode: "RETIRE",
      accountTypeGroupDescription: "Surrender",
    },
    {
      accountTypeCode: "FACLTY",
      accountTypeDescription: "Facility Account",
      accountTypeGroupCode: "FACLTY",
      accountTypeGroupDescription: "Facility",
    },
    {
      accountTypeCode: "GENERAL",
      accountTypeDescription: "General Account",
      accountTypeGroupCode: "GENERAL",
      accountTypeGroupDescription: "General",
    },
    {
      accountTypeCode: "RESERVE",
      accountTypeDescription: "EPA Reserve Account",
      accountTypeGroupCode: "RESERVE",
      accountTypeGroupDescription: "Reserve",
    },
  ],
};

export const transactionTypes = {
  url: `${config.services.mdm.uri}/transaction-type-codes`,
  data: [
    {
      transactionTypeCode: "AD",
      transactionTypeDescription: "Activate Conditional Allowances",
    },
    {
      transactionTypeCode: "AT",
      transactionTypeDescription:
        "Transfer Due to Corrected Energy Conservation",
    },
    {
      transactionTypeCode: "CASURR",
      transactionTypeDescription: "Compliance Assurance Surrender",
    },
    {
      transactionTypeCode: "CC",
      transactionTypeDescription: "Substitution Control by Contract Deduction",
    },
    {
      transactionTypeCode: "CR",
      transactionTypeDescription: "Conservation Issuance",
    },
    {
      transactionTypeCode: "DE",
      transactionTypeDescription: "Reallocation Transfer",
    },
  ],
};

export const sourceCategories = {
  url: `${config.services.mdm.uri}/source-category-codes`,
  data: [
    {
      sourceCategoryCode: "AUTSTMP",
      sourceCategoryDescription: "Automotive Stampings",
    },
    {
      sourceCategoryCode: "BKINCHM",
      sourceCategoryDescription: "Bulk Industrial Chemical",
    },
    {
      sourceCategoryCode: "CEMENTM",
      sourceCategoryDescription: "Cement Manufacturing",
    },
    {
      sourceCategoryCode: "COGEN",
      sourceCategoryDescription: "Cogeneration",
    },
    {
      sourceCategoryCode: "ELECTRC",
      sourceCategoryDescription: "Electric Utility",
    },
  ],
};
export const attributes = {
  url: `${config.services.account.uri}/emissions-compliance/attributes/applicable`,
  data: [
    {
      year: 1996,
      facilityId: 7,
      stateCode: "AL",
      ownerOperator: "Alabama Power Company",
    },
    {
      year: 1996,
      facilityId: 26,
      stateCode: "AL",
      ownerOperator: "Alabama Power Company",
    },
    {
      year: 1996,
      facilityId: 47,
      stateCode: "AL",
      ownerOperator: "Tennessee Valley Authority",
    },
    {
      year: 1996,
      facilityId: 641,
      stateCode: "FL",
      ownerOperator: "Gulf Power Company",
    },
    { year: 1996, facilityId: 641, stateCode: "FL", ownerOperator: null },
    {
      year: 1996,
      facilityId: 642,
      stateCode: "FL",
      ownerOperator: "Gulf Power Company",
    },
    {
      year: 1996,
      facilityId: 645,
      stateCode: "FL",
      ownerOperator: "Tampa Electric Company",
    },
    {
      year: 1996,
      facilityId: 699,
      stateCode: "GA",
      ownerOperator: "Georgia Power Company",
    },
    {
      year: 1996,
      facilityId: 703,
      stateCode: "GA",
      ownerOperator: "Georgia Power Company2",
    },
    {
      year: 1996,
      facilityId: 708,
      stateCode: "GA",
      ownerOperator: "Georgia Power Company3",
    },
    {
      year: 1996,
      facilityId: 709,
      stateCode: "GA",
      ownerOperator: "Georgia Power Company4",
    },
    {
      year: 1996,
      facilityId: 710,
      stateCode: "GA",
      ownerOperator: "Georgia Power Company5",
    },
    {
      year: 1996,
      facilityId: 727,
      stateCode: "GA",
      ownerOperator: "Georgia Power Company6",
    },
    {
      year: 1996,
      facilityId: 728,
      stateCode: "GA",
      ownerOperator: "Georgia Power Company7",
    },
    {
      year: 1996,
      facilityId: 733,
      stateCode: "GA",
      ownerOperator: "Savannah Electric & Power Company",
    },
    {
      year: 1996,
      facilityId: 862,
      stateCode: "IL",
      ownerOperator: "Central Illinois Public Service Company",
    },
    {
      year: 1996,
      facilityId: 863,
      stateCode: "IL",
      ownerOperator: "Central Illinois Public Service Company2",
    },
    {
      year: 1996,
      facilityId: 864,
      stateCode: "IL",
      ownerOperator: "Central Illinois Public Service Company3",
    },
    {
      year: 1996,
      facilityId: 887,
      stateCode: "IL",
      ownerOperator: "Electric Energy, Inc.",
    },
    {
      year: 1996,
      facilityId: 889,
      stateCode: "IL",
      ownerOperator: "Illinois Power Company",
    },
    {
      year: 1996,
      facilityId: 892,
      stateCode: "IL",
      ownerOperator: "Illinois Power Company2",
    },
    {
      year: 1996,
      facilityId: 897,
      stateCode: "IL",
      ownerOperator: "Illinois Power Company3",
    },
    {
      year: 1996,
      facilityId: 990,
      stateCode: "IN",
      ownerOperator: "Indianapolis Power & Light Company",
    },
    {
      year: 1996,
      facilityId: 991,
      stateCode: "IN",
      ownerOperator: "Indianapolis Power & Light Company2",
    },
  ],
};
const filterMapping = [
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 7,
    stateCode: "AL",
    ownerOperator: "Alabama Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 26,
    stateCode: "AL",
    ownerOperator: "Alabama Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 26,
    stateCode: "AL",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 26,
    stateCode: "AL",
    ownerOperator: "Southern Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 47,
    stateCode: "AL",
    ownerOperator: "Tennessee Valley Authority",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 56,
    stateCode: "AL",
    ownerOperator: "PowerSouth Energy Cooperative, Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 641,
    stateCode: "FL",
    ownerOperator: "Florida Power & Light Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 642,
    stateCode: "FL",
    ownerOperator: "Florida Power & Light Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 645,
    stateCode: "FL",
    ownerOperator: "Tampa Electric Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 699,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 703,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 708,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 709,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 710,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 727,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 728,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 733,
    stateCode: "GA",
    ownerOperator: "Georgia Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 861,
    stateCode: "IL",
    ownerOperator: "Illinois Power Generating Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 862,
    stateCode: "IL",
    ownerOperator: "Grand Tower Energy Center, LLC",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 863,
    stateCode: "IL",
    ownerOperator: "AmerenEnergy Medina Valley Cogen, LLC",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 864,
    stateCode: "IL",
    ownerOperator: "AmerenEnergy Medina Valley Cogen, LLC",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 876,
    stateCode: "IL",
    ownerOperator: "Kincaid Generation, LLC",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 887,
    stateCode: "IL",
    ownerOperator: "Electric Energy, Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 889,
    stateCode: "IL",
    ownerOperator: "Dynegy Midwest Generation Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 891,
    stateCode: "IL",
    ownerOperator: "Dynegy Midwest Generation Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 892,
    stateCode: "IL",
    ownerOperator: "Dynegy Midwest Generation Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 897,
    stateCode: "IL",
    ownerOperator: "Dynegy Midwest Generation Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 898,
    stateCode: "IL",
    ownerOperator: "Dynegy Midwest Generation Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 983,
    stateCode: "IN",
    ownerOperator: "Indiana Kentucky Electric Corp",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 988,
    stateCode: "IN",
    ownerOperator: "Indiana Michigan Power Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 990,
    stateCode: "IN",
    ownerOperator: "Indianapolis Power & Light Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 991,
    stateCode: "IN",
    ownerOperator: "Indianapolis Power & Light Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 994,
    stateCode: "IN",
    ownerOperator: "Indianapolis Power & Light Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 995,
    stateCode: "IN",
    ownerOperator: "Northern Indiana Public Service Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 997,
    stateCode: "IN",
    ownerOperator: "Northern Indiana Public Service Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 1001,
    stateCode: "IN",
    ownerOperator: "Duke Energy Indiana, LLC",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 1008,
    stateCode: "IN",
    ownerOperator: "Duke Energy Indiana, LLC",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 1010,
    stateCode: "IN",
    ownerOperator: "Duke Energy Indiana, LLC",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 1010,
    stateCode: "IN",
    ownerOperator: null,
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 1012,
    stateCode: "IN",
    ownerOperator: "Southern Indiana Gas and Electric Company",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 1043,
    stateCode: "IN",
    ownerOperator: "Hoosier Energy REC, Inc.",
  },
  {
    year: "1995",
    programCode: "ARP",
    facilityId: 1048,
    stateCode: "IA",
    ownerOperator: "Interstate Power & Light Company",
  },
];

export const allowanceCompliance = {
  url: `${config.services.account.uri}/allowance-compliance/attributes/applicable`,
  data: filterMapping,
};
export const accountAttributes = {
  url: `${config.services.account.uri}/accounts/attributes/applicable`,
  data: filterMapping,
};

export const allowanceHoldings = {
  url: `${config.services.account.uri}/allowance-holdings/attributes/applicable`,
  data: filterMapping,
};
export const programCodes = {
  url: `${config.services.mdm.uri}/program-codes`,
  data: [
    {
      "programCode": "ARP",
      "programDescription": "Acid Rain Program",
      "compParameterCode": "SO2",
      "programGroupCode": null,
      "programGroupDescription": null,
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": true,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "CAIRNOX",
      "programDescription": "CAIR NOx Annual Program",
      "compParameterCode": "NOX",
      "programGroupCode": "CAIR",
      "programGroupDescription": "Clean Air Interstate Rule",
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": true,
      "retiredIndicator": true,
      "tradingEndDate": "2016-08-10"
    },
    {
      "programCode": "CAIROS",
      "programDescription": "CAIR NOx Ozone Season Program",
      "compParameterCode": "NOX",
      "programGroupCode": "CAIR",
      "programGroupDescription": "Clean Air Interstate Rule",
      "ozoneIndicator": true,
      "annualIndicator": false,
      "allowanceIndicator": true,
      "retiredIndicator": true,
      "tradingEndDate": "2016-08-10"
    },
    {
      "programCode": "CAIRSO2",
      "programDescription": "CAIR SO2 Annual Program",
      "compParameterCode": "SO2",
      "programGroupCode": "CAIR",
      "programGroupDescription": "Clean Air Interstate Rule",
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": true,
      "retiredIndicator": true,
      "tradingEndDate": "2016-08-10"
    },
    {
      "programCode": "CSNOX",
      "programDescription": "Cross-State Air Pollution Rule NOx Annual Program",
      "compParameterCode": "NOX",
      "programGroupCode": "CSAPR",
      "programGroupDescription": "Cross-State Air Pollution Rule",
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": true,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "CSNOXOS",
      "programDescription": "Cross-State Air Pollution Rule NOx Ozone Season Program",
      "compParameterCode": "NOX",
      "programGroupCode": "CSAPR",
      "programGroupDescription": "Cross-State Air Pollution Rule",
      "ozoneIndicator": true,
      "annualIndicator": false,
      "allowanceIndicator": true,
      "retiredIndicator": true,
      "tradingEndDate": "2017-10-23"
    },
    {
      "programCode": "CSOSG1",
      "programDescription": "Cross-State Air Pollution Rule NOx Ozone Season Program Group 1",
      "compParameterCode": "NOX",
      "programGroupCode": "CSAPR",
      "programGroupDescription": "Cross-State Air Pollution Rule",
      "ozoneIndicator": true,
      "annualIndicator": false,
      "allowanceIndicator": true,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "CSOSG2",
      "programDescription": "Cross-State Air Pollution Rule NOx Ozone Season Program Group 2",
      "compParameterCode": "NOX",
      "programGroupCode": "CSAPR",
      "programGroupDescription": "Cross-State Air Pollution Rule",
      "ozoneIndicator": true,
      "annualIndicator": false,
      "allowanceIndicator": true,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "CSSO2G1",
      "programDescription": "Cross-State Air Pollution Rule SO2 Annual Program Group 1",
      "compParameterCode": "SO2",
      "programGroupCode": "CSAPR",
      "programGroupDescription": "Cross-State Air Pollution Rule",
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": true,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "CSSO2G2",
      "programDescription": "Cross-State Air Pollution Rule SO2 Annual Program Group 2",
      "compParameterCode": "SO2",
      "programGroupCode": "CSAPR",
      "programGroupDescription": "Cross-State Air Pollution Rule",
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": true,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "NBP",
      "programDescription": "NOx Budget Trading Program",
      "compParameterCode": "NOX",
      "programGroupCode": null,
      "programGroupDescription": null,
      "ozoneIndicator": true,
      "annualIndicator": false,
      "allowanceIndicator": false,
      "retiredIndicator": true,
      "tradingEndDate": "2009-03-25"
    },
    {
      "programCode": "NHNOX",
      "programDescription": "NH NOx Program",
      "compParameterCode": null,
      "programGroupCode": null,
      "programGroupDescription": null,
      "ozoneIndicator": true,
      "annualIndicator": false,
      "allowanceIndicator": false,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "NSPS4T",
      "programDescription": "New Source Performance Standards subpart TTTT",
      "compParameterCode": null,
      "programGroupCode": null,
      "programGroupDescription": null,
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": false,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "OTC",
      "programDescription": "OTC NOx Budget Program",
      "compParameterCode": "NOX",
      "programGroupCode": null,
      "programGroupDescription": null,
      "ozoneIndicator": true,
      "annualIndicator": false,
      "allowanceIndicator": false,
      "retiredIndicator": true,
      "tradingEndDate": "2003-05-06"
    },
    {
      "programCode": "RGGI",
      "programDescription": "Regional Greenhouse Gas Initiative",
      "compParameterCode": null,
      "programGroupCode": null,
      "programGroupDescription": null,
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": false,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "SIPNOX",
      "programDescription": "SIP NOx Program",
      "compParameterCode": null,
      "programGroupCode": null,
      "programGroupDescription": null,
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": false,
      "retiredIndicator": false,
      "tradingEndDate": null
    },
    {
      "programCode": "TXSO2",
      "programDescription": "Texas SO2 Trading Program",
      "compParameterCode": "SO2",
      "programGroupCode": "TXSO2",
      "programGroupDescription": "Texas SO2 Trading Program",
      "ozoneIndicator": false,
      "annualIndicator": true,
      "allowanceIndicator": true,
      "retiredIndicator": false,
      "tradingEndDate": null
    }
  ],
};
export const facilities = {
  url: `${config.services.facilities.uri}/facilities`,
  data: [
    {
      facilityRecordId: 1,
      facilityId: 3,
      facilityName: "Barry",
      stateCode: "AL",
      links: [
        { rel: "self", href: "/api/facility-mgmt/facilities/1" },
        { rel: "units", href: "/api/facility-mgmt/facilities/1/units" },
        { rel: "stacks", href: "/api/facility-mgmt/facilities/1/stacks" },
        { rel: "owners", href: "/api/facility-mgmt/facilities/1/owners" },
        { rel: "contacts", href: "/api/facility-mgmt/facilities/1/contacts" },
      ],
    },
    {
      facilityRecordId: 2,
      facilityId: 5,
      facilityName: "Chickasaw",
      stateCode: "AL",
      links: [
        { rel: "self", href: "/api/facility-mgmt/facilities/2" },
        { rel: "units", href: "/api/facility-mgmt/facilities/2/units" },
        { rel: "stacks", href: "/api/facility-mgmt/facilities/2/stacks" },
        { rel: "owners", href: "/api/facility-mgmt/facilities/2/owners" },
        { rel: "contacts", href: "/api/facility-mgmt/facilities/2/contacts" },
      ],
    },
  ],
};

export const ownerOperators = {
  url: `${config.services.account.uri}/emissions-compliance/owner-operators`,
  data: [
    { ownerOperator: "5380 Frontier Ave Energy Company LLC", ownType: "OPR" },
    { ownerOperator: "5380 Frontier Ave Energy Company LLC", ownType: "OWN" },
    { ownerOperator: "ABB Energy Ventures, Inc.", ownType: "OPR" },
    { ownerOperator: "Acadia Power Partners, LLC", ownType: "OWN" },
    { ownerOperator: "A/C Power - Colver Operations", ownType: "OPR" },
    { ownerOperator: "Adams-Columbia Electric Cooperative", ownType: "OWN" },
    { ownerOperator: "AdvanSix Resins and Chemicals, LLC", ownType: "OPR" },
    { ownerOperator: "AdvanSix Resins and Chemicals, LLC", ownType: "OWN" },
    { ownerOperator: "AEE 2, LLC", ownType: "OWN" },
    { ownerOperator: "AEP Energy Partners Inc", ownType: "OWN" },
    { ownerOperator: "AEP Generation Resources, Inc.", ownType: "BTH" },
    { ownerOperator: "AEP1 Generation Resources, Inc.", ownType: "OPR" },
    { ownerOperator: "AEP2 Generation Resources, Inc.", ownType: "OWN" },
    { ownerOperator: "AEP3 Pro Serv, Inc", ownType: "OPR" },
  ],
};

export const hourlyEmissions = {
  url: `${config.services.emissions}/emissions/apportioned/hourly`,
  data: []
}
