export const dataPreviewColumns = {
    "State"	: "75px",
    "Facility Name" :	"130px",
    "Facility ID"	: "105px",
    "Unit ID" :	"85px",
    "Associated Stacks"	: "160px",
    "Year" :	"65px",
    "Program" :	"135px",
    "EPA Region" :	"115px",
    "NERC Region"	:"125px",
    "County" :	"85px",
    "County Code"	: "125px",
    "FIPS Code" :	"105px",
    "Source Category" :	"150px",
    "Latitude" :"95px",
    "Longitude"	: "105px",
    "Owner/Operator" :	"150px",
    "SO2 Phase"	: "110px",
    "NOX Phase"	: "110px",
    "Primary Fuel" :"160px",
    "Secondary Fuel" :	"180px",
    "Unit Type"	: "105px",
    "SO2 Controls"	: "125px",
    "PM Controls"	: "120px",
    "NOX Controls"	: "130px",
    "Hg Controls"	: "120px",
    "Commercial Operation Date" :	"215px",
    "Operating Status" :	"155px",
    "Max Hourly HI Rate" :	"215px",
    "Associated Generators & Nameplate Capacity"	: "265px"
};
