export const HOURLY_EMISSIONS = {
  UPDATE_TIME_PERIOD : "UPDATE_TIME_PERIOD",
  UPDATE_PROGRAM_SELECTION : "UPDATE_PROGRAM_SELECTION",
  UPDATE_FACILITY_SELECTION : "UPDATE_FACILITY_SELECTION",
  UPDATE_UNIT_TYPE_SELECTION: "UPDATE_UNIT_TYPE_SELECTION",
  UPDATE_FUEL_TYPE_SELECTION: "UPDATE_FUEL_TYPE_SELECTION",
  UPDATE_STATE_SELECTION: "UPDATE_STATE_SELECTION",
  RESET_FILTER: "RESET_FILTER",
};
export const UPDATE_SELECTED_DATATYPE = "UPDATE_SELECTED_DATATYPE";
export const UPDATE_SELECTED_DATASUBTYPE = "UPDATE_SELECTED_DATASUBTYPE";
export const ADD_APPLIED_FILTER = "ADD_APPLIED_FILTER";
export const REMOVE_APPLIED_FILTER = "REMOVE_APPLIED_FILTER";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const LOAD_HOURLY_EMISSIONS_SUCCESS = "LOAD_HOURLY_EMISSIONS_SUCCESS";
export const RESET_DATA_PREVIEW = "RESET_DATA_PREVIEW";
export const LOAD_EMISSIONS_PROGRAMS_SUCCESS = "LOAD_EMISSIONS_PROGRAMS_SUCCESS";
export const LOAD_FACILITIES_SUCCESS = "LOAD_FACILITIES_SUCCESS";
export const LOAD_EMISSIONS_UNIT_TYPES_SUCCESS = "LOAD_EMISSIONS_UNIT_TYPES_SUCCESS";
export const LOAD_EMISSIONS_FUEL_TYPES_SUCCESS = "LOAD_EMISSIONS_FUEL_TYPES_SUCCESS";
export const LOAD_EMISSIONS_STATES_SUCCESS = "LOAD_EMISSIONS_STATES_SUCCESS";
