//filter updates
export const UPDATE_TIME_PERIOD = "UPDATE_TIME_PERIOD";
export const UPDATE_PROGRAM_SELECTION = "UPDATE_PROGRAM_SELECTION";
export const UPDATE_FACILITY_SELECTION ="UPDATE_FACILITY_SELECTION";
export const UPDATE_UNIT_TYPE_SELECTION = "UPDATE_UNIT_TYPE_SELECTION";
export const UPDATE_FUEL_TYPE_SELECTION = "UPDATE_FUEL_TYPE_SELECTION";
export const UPDATE_STATE_SELECTION = "UPDATE_STATE_SELECTION";
export const UPDATE_CONTROL_TECHNOLOGY_SELECTION = "UPDATE_CONTROL_TECHNOLOGY_SELECTION";

//load filter data
export const LOAD_PROGRAMS_SUCCESS = "LOAD_PROGRAMS_SUCCESS";
export const LOAD_FACILITIES_SUCCESS = "LOAD_FACILITIES_SUCCESS";
export const LOAD_UNIT_TYPES_SUCCESS = "LOAD_UNIT_TYPES_SUCCESS";
export const LOAD_FUEL_TYPES_SUCCESS = "LOAD_FUEL_TYPES_SUCCESS";
export const LOAD_STATES_SUCCESS = "LOAD_STATES_SUCCESS";
export const LOAD_CONTROL_TECHNOLOGIES_SUCCESS = "LOAD_CONTROL_TECHNOLOGIES_SUCCESS";

//filter reset
export const RESET_FILTER = "RESET_FILTER";

//applied filter operations
export const ADD_APPLIED_FILTER = "ADD_APPLIED_FILTER";
export const REMOVE_APPLIED_FILTER = "REMOVE_APPLIED_FILTER";

//update cdd data type and subytpe
export const UPDATE_SELECTED_DATATYPE = "UPDATE_SELECTED_DATATYPE";
export const UPDATE_SELECTED_DATASUBTYPE = "UPDATE_SELECTED_DATASUBTYPE";

//API call
export const BEGIN_API_CALL = "BEGIN_API_CALL";

//data preview
export const LOAD_DATA_PREVIEW_SUCCESS = "LOAD_DATA_PREVIEW_SUCCESS";
export const RESET_DATA_PREVIEW = "RESET_DATA_PREVIEW";
